config/routes.rb
TheCityEvents::Application.routes.draw do

  get 'auth/failure'=> 'application#failure',:as => :failure

  post "webhooks/createCityUser"
  post "webhooks/createFamilyMember"

  resources :city_users do
    get :autocomplete_for_city_user_full_name, :on => :collection
  end

  resources :events do
    member do
      get 'register'
    end
  end

  resources :registrations do
    member do
      get 'summary'
    end
  end

  namespace :admin do
    resources :events
    resources :coupons
    get 'reports/summary/:id' => 'reports#summary',:as => :summary
    get 'reports/detail/:id' => 'reports#detail', :as => :detail

  end

  get  "/admin" => "admin/events#index"

  match "adminLogin" => "sessions#adminLogin",via: [:post]
  match "clientLogin" => "sessions#clientLogin",via: [:get,:post]

  match '/safari_cookie', to: 'sessions#safari_cookie' ,via: [:get,:post]

  match "/auth/:provider/callback" => "sessions#create",via: [:get]
  match "/signout" => "sessions#destroy", :as => :signo,via: [:get]

  match "registrations/verify_coupon" => "registrations#verify_coupon" ,via: [:post]

  match "registrations/redeem_coupon" => "registrations#redeem_coupon" ,via: [:post]

  match "/processfeed" => "datafeeds#parsefeed",via: [:post]

  match "upcoming-events" => "home#upcoming" , :as => "upcoming" ,via: [:get,:post]

  match "registration/:event_id" => "home#registration" , :as => "event_registration" ,via: [:get,:post]

  match "registration/:id/summary" => "home#summary" , :as => "event_registration_summary" ,via: [:get,:post]

  match "complete" => "home#create" , :as => "complete_registration" ,via: [:post]

  post "/" => "home#index"
  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :addons , :dependent => :destroy
  has_one :registration
  has_many :registrations

  accepts_nested_attributes_for :addons , :reject_if => lambda { |a| a[:title].blank? },:allow_destroy => true
  validates_presence_of :title, :start_date, :end_date, :start_time, :end_time, :base_price, :max_price, :seats

  validates_numericality_of :base_price,
                            :greater_than_or_equal_to =>0,
                            :message => "invalid base price"

  validates_numericality_of :max_price,
                            :greater_than_or_equal_to =>0,
                            :message => "invalid max price"

  validates_numericality_of :seats, :only_integer =>true,
                            :greater_than_or_equal_to =>0,
                            :message => "invalid seats"
  attr_accessor :status

  scope :all, where('archive = ?', :false)

  scope :archived, where('archive = ?', :true)


  def status(current_user)
   if(current_user.nil?)
     "new"
   else
     registration =Registration.find_by_user_id_and_event_id(current_user.id,self.id)
     if(registration)
       if registration.amount_paid >= registration.amount_payable
         "registered"
       elsif registration.amount_paid < registration.amount_payable
         "pending"
       end
     else
       "new"
     end
   end

  end

  #def exportCSV(options = {})
  #
  #  registrations =self.registrations.where("amount_paid=amount_payable")
  #
  #  CSV.generate(options) do |csv|
  #   # csv << ['date','registration','guests']
  #   registrations.each do |r|
  #     #registration
  #     row =[r.created_at.strftime("%m/%d/%Y"),r.user.user_name]
  #     #guests
  #     r.registration_guests.each do  |guest|
  #       row += [guest.first,guest.last,guest.address.blank? ? '-' : guest.address,guest.city.blank? ? '-' : guest.city,guest.state.blank? ? '-' : guest.state]
  #     end
  #     #addons
  #     r.registration_addons.each do |addon|
  #       row += [getTitle(addon, false)]
  #     end
  #
  #     csv << row
  #   end
  #
  #
  #
  #  end
  #
  #end

  def exportCSV(options = {})
    event = self
    registrations =event.registrations.where("amount_paid=amount_payable")

    CSV.generate(options) do |csv|
       #Header
       csv << ['Date','Registration','Coupon','Total']+addons_headings(event, true)+['Guests']+addons_headings(event, false) #+['Guest Total']
       registrations.each do |r|
         #Date and registration Field
         row =[r.created_at.strftime("%m/%d/%Y"),r.user.user_name,r.coupon==''? ' ' : r.coupon+'('+"$%.2f" % r.coupon_amount+')',"$%.2f" % r.amount_payable]
         #addon values for registration specific Fields
         row += registration_specific_choices(event, r)


         #add guests
         price =0.00
         r.registration_guests.each.with_index do |guest,index|
           #addons place holders for registrant specific Fields
           row2 =[]
           if(index>0)
             row2 +=[' ',' ',' ',' ']
             row2 += addons_headings_placeholder(event, true)
           end
           row2  +=[guest.first+' '+guest.last]
           event.addons.where(:registration_type => false).each do |a|
               addon =guest.registration_addons.where(:addon_id => a.id).first
               if addon
                 row2.push(getTitle(addon, false))
               else
                 row2.push(' ')
               end
           end

           #Guest Total
           #a = RegistrationAddon.where(:registration_guest_id => guest.id).joins(:registration_choices).sum("choice_value*choice_price")
           #row2.push( a>0 ? "$ %.2f" % a : ' ')

           if(index==0)
             #First Row
             csv << row+row2
           else
             csv << row2
           end

         end


       end


    end

  end

  def addons_headings(event, state)
    result =[]
    event.addons.where(:registration_type => state).each do |a|
      result.push(a.title)
    end
    result
  end

  def addons_headings_placeholder(event, state)
    result =[]
    event.addons.where(:registration_type => state).each do |a|
      result.push('')
    end
    result
  end

  def registration_specific_choices(event, r)
    choices=[]
    event.addons.where(:registration_type => true).each do |a|
      addon =r.registration_addons.where(:addon_id => a.id).first
      choices.push(getTitle(addon, false))
    end
    choices
  end





  def getTitle(a, empty)

    case a.addon.addon_type
      when "Addons::Text"
        a.addon_value=='' ? ' ' : a.addon_value
      when "Addons::Dropdown"
        a.addon_value=='' ? ' ' : Choice.find_by_id(a.addon_value) ? Choice.find_by_id(a.addon_value).title : ' '
      when "Addons::Checkbox"
        choices = a.registration_choices.where(:choice_value => 1)
        if choices.count>0
          choices.map { |c| c.choice.title }.join ','
        else
          "-"
        end
      when "Addons::Scale"
        choices = a.registration_choices
        if choices.count>0
          choices.map { |c| "#{c.choice.title}-#{c.choice_value.nil? ? 0 : c.choice_value }" }.join ' | '
        else
          empty ? "" : " "
        end
      else
        a.addon.addon_type
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

require 'addon_form'
  def index
    @events = Event.all.order(start_date: :desc)
  end
  def show
    @event = Event.find(params[:id])
  end
  def new
    @admin_event = Event.new
    1.times do
      addon = @admin_event.addons.build
      1.times { addon.choices.build }
    end
  end

  # POST /events
  # POST /events.json
  def create

    @admin_event = Event.new(event_params)

    respond_to do |format|
      if @admin_event.save
        format.html { redirect_to admin_events_url, notice: 'Event was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy

    Event.find(params[:id]).update :archive => true

    return redirect_to admin_events_url, notice: 'Event was successfully deleted.'

  end
  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :start_date, :end_date, :start_time, :end_time, :base_price, :max_price, :seats,:content,addons_attributes: [:addon_type,:registration_type,:title,:_destroy,choices_attributes:[:title,:price,:range_from,:range_to,:_destroy]])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def index

    @registered_events = current_user.events.where("amount_paid=amount_payable")
    @pending_registrations = current_user.events.where("amount_paid<>amount_payable")

    @up_coming_events= Event.where("start_date > ? and id NOT IN (?)",Time.now.strftime('%Y-%m-%d'),current_user.events.select("events.id").load).order("start_date desc").load

  end

  def show
    begin
      @event =current_user.events.find(params[:id])
    rescue
      redirect_to events_path, :notice => "Well, that wasn't supposed to happen."
    end

  end

  def register

    @event = validate_event(params[:id])

    if @event.nil?
      redirect_to events_path, :notice => "Sorry, event has been passed."
      return
    end

    @registration = Registration.new(:event => @event)

    @registration.family_members = current_user.family_members.where('city_user_id != ?', current_user.user_id).all(:order => :city_user_id)

    @event.addons.order('id').collect do |addon|
      a= @registration.registration_addons.build(addon_id: addon.id)
      addon.choices.order('id').collect do |choice|
        a.registration_choices.build(choice_id: choice.id,choice_price: choice.price)
      end
    end


  end

  #Creates a new event
  def create

    @registration = current_user.registrations.new(event_params)

    respond_to do |format|
      if @registration.save
        if @registration.amount_payable == 0.0
          format.html { redirect_to :controller => 'events', notice: 'Event was successfully registered.'  }
        else
          format.html { redirect_to :controller => 'registrations', :action => 'summary', :id => @registration.id,notice: 'Event was successfully registered.' }
        end

      else
        @event =validate_event(event_params[:event_id])
        @registration.family_members = current_user.family_members.where('city_user_id != ?', current_user.user_id).all(:order => :city_user_id)
        format.html { render action: 'register' }
      end
    end

  end


  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:registration).permit(:event_id,:amount_total,:amount_payable,:max_price,
                                         :registration_addons_attributes => [:addon_id,:addon_value,:registration_choices_attributes =>[:choice_id,:choice_value,:choice_price]],
                                         :registration_guests_attributes => [:city_user_id,:first,:last,:email,:primary_phone,:address,:city,:state,:coming,:registration_addons_attributes => [:addon_id,:addon_value,:registration_choices_attributes =>[:choice_id,:choice_value,:choice_price]]])


  end

  def validate_event(event_id)
    event_id = Event.find(event_id) #Get Event id from params and verify it
    #Avoid SQL Injection
    Event.where("id= ? and start_date >= ? ",event_id.id,Time.now.strftime('%Y-%m-%d')).order("start_date desc").first
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def person_image(gender,imgDefault="no_image_male.jpg")
    image =imgDefault

    if gender == 'Male'
      image =imgDefault
    end

    if gender == 'Female'
        image =imgDefault
    end


    request.protocol+request.host_with_port+image_path(image)
  end

  #Function to choose which partial to render based on controller for Event Registration views
  def render_addon_form_helper(a, addon_form,type)
    if a.addon.registration_type==type
      partial = a.addon.addon_type.to_s.split("::").last.downcase
      #If using the outside-City controller ("Home") render one partial, otherwise use in-City partial
      if params[:controller]=='home'
        render partial: "home/addons/#{partial}", locals: { addon_form: addon_form, a: a }
      else
        render partial: "events/addons/#{partial}", locals: { addon_form: addon_form, a: a }
      end
    end
  end

  def fields_person_specific_options(f,registration)
     render(partial: "events/person_options", locals: { :f => f,:registration => registration,:person_id => "",:person_id_name=>"",:display_state => true })
  end

  def link_to_add_person_specific_options(f,registration,cssClass="left btn btn_mini",personTemplate='events/person',defaultAction=0)

    person =render(partial: personTemplate,locals: {:f => f,:registration => registration, :person_id => "{demo_id}",
                                                    :person_picture => person_image('no_image_male.jpg'),
                                                    :person_name =>  "{demo_name}",
                                                    :checked_state => true,
                                                    :display_state => true})

    fields =fields_person_specific_options(f,registration)

    if(cssClass=='plus')
      link_to  '', 'javascript:void(0);',
               :onclick => h("add_person_fields(this, \"#{registration}\", \"#{escape_javascript(fields)}\",\"#{escape_javascript(person)}\",#{defaultAction});"),
               :class => cssClass
    else
      link_to image_tag('add_icon.png', :border=>0,:alt=>'Add_icon', :style => 'margin-right: 3px; float: left;'), 'javascript:void(0);',
              :onclick => h("add_person_fields(this, \"#{registration}\", \"#{escape_javascript(fields)}\",\"#{escape_javascript(person)}\",#{defaultAction});"),
              :class => cssClass
    end




  end
  def link_to_toggle_person(f,registration,person_id,person_name)
    h("personCartToggle(this,\"#{person_id}\",\"#{person_name}\",\"#{registration}\",\"#{escape_javascript(fields_person_specific_options(f,registration))}\");")
  end

  def link_to_add_guest_specific_options(name,f,registration,cssClass="",guestPartial='events/guest')

    guest =render(partial: guestPartial,locals: { :f => f,:registration => registration})

    fields= render(partial: "events/person_options", locals: { :f => f,:registration => registration,:person_id => "{guest_id}",:person_id_name=>"{guest_name}",:display_state => true })


    link_to name, 'javascript:void(0);',
            :class => cssClass,
            :onclick => h("addGuest(\"#{registration}\", \"#{escape_javascript(fields)}\",\"#{escape_javascript(guest)}\");")

  end

  def add_choice_data_attributes(c)
    " data-title = #{c.choice.title}\ data-price = #{c.choice_price} "
  end
end

app/views/admin/events/_addon_fields.erb
<ul class="fields fieldsContainer">
    <h3 class="handle">Addon</h3>
    <li class="grid-4-12">
      <%= f.label :addon_type %>
      <%= f.select :addon_type, AddonForm::ADDON_TYPES, {:prompt => "Select Addon"}, {:required => true,:class => "ctrl_select addon_type",:onchange=>"addOnTypes_handler(this);"} %>
    </li>
    <li class="grid-6-12">
      <label>&nbsp;</label>
      <%= f.input :registration_type,:label=>false,collection:[['Registration Specific',true],['Registrant Specific',false]], as: :radio_buttons %>
    </li>
    <li class="grid-2-12">
      <label>&nbsp;</label>
      <%= link_to_remove_fields "Remove this Addon", f %>
    </li>
    <li class="grid-12-12">
      <label form="mj_song">Title</label>
      <%= f.input :title,:label => false %>
    </li>
    <li class="grid-12-12 choices" >
      <h4 class="rule" >Choices</h4>
      <fieldset style="background-image:none;margin-top:-10px !important;" class="choiceContainer">
          <%= f.fields_for :choices do |choice| %>
                <%= render 'choice_fields', :f => choice %>
          <% end %>
        <li class="form_footer">
          <%= link_to_add_fields "Add Choice", f, :choices %>
        </li>
      </fieldset>
    </li>
  </ul>

app/views/admin/events/_choice_fields.erb
  <ul class="fields" style="margin-top:0px !important;" >
    <li class="grid-4-12" >
      <%= f.input :title %>
    </li>

    <li class="grid-2-12 price">
      <%= f.input :price, :input_html => {:onkeypress => "return isNumberKey(event)",:value=>'0.00',:class => "decimal2"} %>
    </li>

    <li class="grid-2-12" style = "display:none;">
      <%= f.input :range_from, :input_html => { :class => "range_from", :onblur => "validateRange(this);", :onkeypress => "return isNumberKey(event)"} %>
    </li>

    <li class="grid-2-12" style = "display:none;">
      <%= f.input :range_to, :input_html => { :class => "range_to",:onblur => "validateRange(this);",:onkeypress => "return isNumberKey(event)" } %>
    </li>
    <li class="grid-2-12" style="padding: 5px;">
      <label form="first_name">&nbsp;</label>
      <%= link_to_remove_fields "Remove", f %>
      <%= image_tag('arrow-cursor-drag.png',size: "16x16",class: "choiceHandle") %>
    </li>
  </ul>

app/views/admin/events/_form.html.erb
<%= stylesheet_link_tag "events_form", :media => "all" %>

<%= simple_form_for(@admin_event, url: admin_events_path(@admin_event)) do |f| %>
    <% if @admin_event.errors.any? %>
        <div id="error_explanation" class="prettyprint">
          <h2><%= pluralize(@admin_event.errors.count, "error") %> prohibited this event from being saved:</h2>
          <ul>
            <% @admin_event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <fieldset  >
      <ul id="list_events">
        <li class="grid-12-12">
          <%= f.input :title %>
        </li>
        <li class="grid-12-12">
          <!--<textarea id="content" name="content"></textarea>-->
          <label class="string control-label" for="event_content">Description</label>
          <%= f.text_area :content,size: "20x20" %>
        </li>
        <li class="grid-6-12">
          <label class="string control-label" for="event_start_date">Start Date</label>
          <%= f.text_field :start_date %>
        </li>
        <li class="grid-6-12">
          <label class="string control-label" for="event_end_date">End Date</label>
          <%= f.text_field :end_date %>
        </li>

        <li class="grid-6-12">
          <%= f.input :start_time, as: :time, :input_html => {class: 'ctrl_time'} %>
        </li>
        <li class="grid-6-12">
          <%= f.input :end_time, as: :time, :input_html => {class: 'ctrl_time'} %>
        </li>
        <li class="grid-4-12">
          <%= f.input :base_price, :input_html => {class: 'ctrl_numeric decimal2', :value => '0.00',:onkeypress => "return isNumberKey(event)"} %>
        </li>
        <li class="grid-4-12">
          <%= f.input :max_price, :input_html => {class: 'ctrl_numeric decimal2', :value => '0.00', :onkeypress => "return isNumberKey(event)"} %>
        </li>
        <li class="grid-4-12">
          <%= f.input :seats, :input_html => {class: 'ctrl_numeric', :onkeypress => "return isNumberKey(event)"} %>
        </li>
        <li class="grid-12-12">
          <h2 class="rule">Addons</h2>
          <fieldset class="addonContainer"  style="background-image:none;padding:0px !important;" >
            <%= f.fields_for :addons do |addon| %>
                <%= render 'addon_fields', :f => addon %>
            <% end %>

          </fieldset>
          <ul class="form_footer">
            <li>
              <%= link_to_add_fields "Add New AddOn", f, :addons %>
            </li>
          </ul>
        </li>
        <!--<li>

        </li>-->
        <li class="form_footer">
          <%= f.submit :class => 'left btn btn_go', :onclick => "return validateform();" %>
          <%= link_to "Cancel",admin_events_path,:class => "btn btn_cancel left" %>
        </li>

      </ul>
    </fieldset>




<% end %>


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

<script type="text/javascript">
    $(function()
    {
        $('#event_content').redactor();

        $( "#event_start_date" ).datepicker({ dateFormat: 'dd/mm/yy' });
        $( "#event_end_date" ).datepicker({ dateFormat: 'dd/mm/yy' });

    });
</script>

app/views/admin/events/index.html.erb
<%= render 'admin/header' %>

<table id='admin_events' class='datatable with_stripes autosort'>
  <thead>
  <tr>
    <th>Title</th>
    <th data-autosort="true" data-sortdir="desc">Start Date</th>
    <th>End Date</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
      <tr id="<%= dom_id(event) %>">
        <td><%= link_to event.title,admin_event_path(event.id) %></td>
        <td><%= event.start_date.strftime("%m/%d/%Y") %></td>
        <td><%= event.end_date.strftime("%m/%d/%Y") %></td>
        <td><%= event.start_time.strftime("%I:%M%p") %></td>
        <td><%= event.end_time.strftime("%I:%M%p") %></td>
        <td> <%= link_to 'Delete',admin_event_path(event),
                         data: { confirm: 'Are you sure?' },
                         :method => :delete,
                         :class => "btn btn_stop btn_mini" %> |
          <%= link_to 'Report',admin_detail_path(event.id),:class => "btn btn_neutral btn_mini" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="grid-12-12">
   <%= link_to 'New Event',new_admin_event_path,html_options = {:class => 'btn btn_go'}%>
   <%= link_to 'Generate Coupons',admin_coupons_path,html_options = {:class => 'btn btn_go'}%>

</div>

<%= render 'admin/footer' %>

app/views/admin/events/new.html.erb
<%= render 'admin/header' %>

<h1>New event</h1>

<%= render 'form' %>


<%= render 'admin/footer' %>

app/views/admin/events/show.html.erb
<fieldset>
  <header class="center_stage">
    <h1> <%= @event.title %></h1>
    <div class="context_bar"></div>

  </header>

   <%= render "admin/event_header" %>
  <div class="grid_8 rule"></div>
  <h4>Event Description </h4>
  <%= @event.content.nil? ? '' : @event.content.html_safe  %>
  <br/><br/>
  <% @event.addons.order('id').each  do |add| %>
      <h4 class=""><%= add.title %></h4><div class="grid_8 rule"></div>
      <ul>
        <li class="grid-12-12"><strong>Type : </strong><%= add.addon_type.split('::')[1] %> - <%= add.registration_type? ? "Registration Specific": "Registrant Specific" %> </li>

        <% if add.choices.count > 0 %>
            <h4 class="rule">
              Choices
            </h4>
            <% add.choices.each  do |choice| %>
                <ol>
                  <li class="grid-6-12" data-value="<%= choice.id %>"><%= choice.title %></li>
                  <li class="grid-2-12">Price: <%= '$%.2f' % choice.price %></li>
                  <li class="grid-4-12">
                    <% if add.addon_type == "Addons::Scale" %>
                    Range From: <%= choice.range_from %> to <%= choice.range_to %>
                    <% else %>
                     &nbsp;
                    <% end %>
                  </li>

                </ol>
            <% end %>
        <% end %>
      </ul>
  <% end %>

</fieldset>

<%= render 'admin/footer' %>