config/routes.rb
TheCityEvents::Application.routes.draw do

  get 'auth/failure'=> 'application#failure',:as => :failure

  post "webhooks/createCityUser"
  post "webhooks/createFamilyMember"

  resources :city_users do
    get :autocomplete_for_city_user_full_name, :on => :collection
  end

  resources :events do
    member do
      get 'register'
    end
  end

  resources :registrations do
    member do
      get 'summary'
    end
  end

  namespace :admin do
    resources :events
    resources :coupons
    get 'reports/summary/:id' => 'reports#summary',:as => :summary
    get 'reports/detail/:id' => 'reports#detail', :as => :detail

  end

  get  "/admin" => "admin/events#index"

  match "adminLogin" => "sessions#adminLogin",via: [:post]
  match "clientLogin" => "sessions#clientLogin",via: [:get,:post]

  match '/safari_cookie', to: 'sessions#safari_cookie' ,via: [:get,:post]

  match "/auth/:provider/callback" => "sessions#create",via: [:get]
  match "/signout" => "sessions#destroy", :as => :signo,via: [:get]

  match "registrations/verify_coupon" => "registrations#verify_coupon" ,via: [:post]

  match "registrations/redeem_coupon" => "registrations#redeem_coupon" ,via: [:post]

  match "/processfeed" => "datafeeds#parsefeed",via: [:post]

  match "upcoming-events" => "home#upcoming" , :as => "upcoming" ,via: [:get,:post]

  match "registration/:event_id" => "home#registration" , :as => "event_registration" ,via: [:get,:post]

  match "registration/:id/summary" => "home#summary" , :as => "event_registration_summary" ,via: [:get,:post]

  match "complete" => "home#create" , :as => "complete_registration" ,via: [:post]

  post "/" => "home#index"
  root 'home#index'

end

app/views/admin/_event_header.erb
<div class="grid_2 omega"><strong>Start Date:</strong> <%= @event.start_date.strftime("%m/%d/%Y") %></div>
<div class="grid_2 omega"><strong>End Date:</strong> <%= @event.end_date.strftime("%m/%d/%Y") %></div>
<div class="grid_2 omega"><strong>Start Time:</strong> <%= @event.start_time.strftime("%I:%M%p") %></div>
<div class="grid_2 omega"><strong>End Time:</strong> <%= @event.end_time.strftime("%I:%M%p") %></div>

<div class="grid_2 omega"><strong>Base Price:</strong> <%= "$%.2f" % @event.base_price %></div>
<div class="grid_2 omega"><strong>Max Price:</strong> <%= "$%.2f" % @event.max_price %></div>
<div class="grid_2 omega">&nbsp;</div>
<div class="grid_2 omega">&nbsp;</div>
<br/>

app/views/admin/_footer.html.erb
<div class="grid_8 footer">
    <% if current_city_user.nil? %>
        Sign in
    <% else %>
        <% if current_city_user.staff? %>
            <%= link_to 'Events Home',upcoming_path,:class => 'btn .btn_go' %>
            <%= link_to 'Events Admin',admin_path,:class => 'btn .btn_go' %>
        <% end %>
    <% end %>
</div>

app/views/admin/_header.erb
<header class="center_stage">
<h1>Events Registration (Admin)</h1>
  <p>
    <% if current_user.nil? %>
        Sign in
    <% else %>
        Welcome,<%= "#{current_user.first} #{current_user.last}" %>
    <% end %>
  </p>
</header>