config/routes.rb
TheCityEvents::Application.routes.draw do

  get 'auth/failure'=> 'application#failure',:as => :failure

  post "webhooks/createCityUser"
  post "webhooks/createFamilyMember"

  resources :city_users do
    get :autocomplete_for_city_user_full_name, :on => :collection
  end

  resources :events do
    member do
      get 'register'
    end
  end

  resources :registrations do
    member do
      get 'summary'
    end
  end

  namespace :admin do
    resources :events
    resources :coupons
    get 'reports/summary/:id' => 'reports#summary',:as => :summary
    get 'reports/detail/:id' => 'reports#detail', :as => :detail

  end

  get  "/admin" => "admin/events#index"

  match "adminLogin" => "sessions#adminLogin",via: [:post]
  match "clientLogin" => "sessions#clientLogin",via: [:get,:post]

  match '/safari_cookie', to: 'sessions#safari_cookie' ,via: [:get,:post]

  match "/auth/:provider/callback" => "sessions#create",via: [:get]
  match "/signout" => "sessions#destroy", :as => :signo,via: [:get]

  match "registrations/verify_coupon" => "registrations#verify_coupon" ,via: [:post]

  match "registrations/redeem_coupon" => "registrations#redeem_coupon" ,via: [:post]

  match "/processfeed" => "datafeeds#parsefeed",via: [:post]

  match "upcoming-events" => "home#upcoming" , :as => "upcoming" ,via: [:get,:post]

  match "registration/:event_id" => "home#registration" , :as => "event_registration" ,via: [:get,:post]

  match "registration/:id/summary" => "home#summary" , :as => "event_registration_summary" ,via: [:get,:post]

  match "complete" => "home#create" , :as => "complete_registration" ,via: [:post]

  post "/" => "home#index"
  root 'home#index'

end

app/controllers/home_controller.rb
require 'cart_encryption'
require 'rc_auth'
class HomeController < ApplicationController
  include CartEncryption
  include FoxySync

  skip_before_filter :verify_authenticity_token, :require_login

  # These pages shouldn't be accessible once the user has paid
  before_filter :redirect_when_paid, only: :summary

  # Redirect to upcoming events if already registered
  before_filter :redirect_when_already_registered, only: :registration

  layout "frontend"



  #display home page
  def index
    @city_user = CityUser.new

    if params.key?(:city_data)
      @raw_city_data = params[:city_data]
      @raw_city_data_iv = params[:city_data_iv]
    elsif cookies[:city_data].present?
      @raw_city_data = cookies[:city_data]
      @raw_city_data_iv = cookies[:city_data_iv]
    else
      @raw_city_data = nil
      @raw_city_data_iv = nil
    end

    if @raw_city_data.present? and @raw_city_data_iv.present?
      @decrypted_city_data = RcAuth::decrypt_city_data(@raw_city_data, @raw_city_data_iv, TheCityEvents::THE_CITY_SECRET[0, 32])
    end

    json = @decrypted_city_data

    if not json.nil? and not json.empty?
      data = JSON.restore(json)

      user = User.find_by_user_id(data['user_id'].to_s)
      if (user.nil?)
        client = TheCity::User.load_by_id(data['user_id'])
        user =User.create_with_token(data, client)
      end
      cookies[:user_id] = user.id
      session[:user_id] = user.id

      #Set Current Logon  User
      @current_user = User.find(session[:user_id]) if session[:user_id]

      redirect_to upcoming_path

    end

  end


  #show upcoming page
  def upcoming

    if request.method == "POST"
      set_user_login
    end

    if current_user.nil?
      redirect_to root_path, notice: 'No city user selected!.'
    end



    title=''
    if params[:title].present?
      title =params[:title]
    end
    @events = Event.where("start_date > ? and lower(title) LIKE ? ", Time.now.strftime('%Y-%m-%d'),"%#{ title.downcase }%").paginate(:page => params[:page], :per_page => params[:limit]).order("start_date")

  end

  #show registration page
  def registration
    if request.method =="POST"
        #//////
    else
      @event = validate_event(params[:event_id])

      if @event.nil?
        redirect_to events_path, :notice => "Sorry, event has been passed."
        return
      end

      @registration = Registration.new(:event => @event)

      if current_user.nil?
        redirect_to upcoming_path, :notice => "Sorry, no city user."
        return
      end

      @registration.family_members = current_user.family_members.where('city_user_id != ?', current_user.user_id).all(:order => :city_user_id)

      @event.addons.order('id').collect do |addon|
        a= @registration.registration_addons.build(addon_id: addon.id)
        addon.choices.order('id').collect do |choice|
          a.registration_choices.build(choice_id: choice.id,choice_price: choice.price)
        end
      end

    end

  end

  #complete registration
  def create

    @registration = current_user.registrations.new(event_params)

    respond_to do |format|
      if @registration.save
        if @registration.amount_payable == 0.0
          format.html { redirect_to upcoming_url }
        else
          format.html { redirect_to event_registration_summary_url(:id => @registration.id) }
        end
      else
        @event =validate_event(event_params[:event_id])
        @registration.family_members = current_user.family_members.where('city_user_id != ?', current_user.user_id).all(:order => :city_user_id)
        format.html { render action: 'registration' }
      end
    end

  end
  #show summary page
  def summary
    @registration = Registration.find(params[:id])
    if @registration.amount_payable == @registration.amount_paid
      redirect_to upcoming_url,notice: 'Event was successfully registered.'
    end
  end

  private

  def set_user_login
    #Set Current City User
    user_id =   params[:city_user][:city_user_id]
    if user_id.split('(')[1]
      user_id = user_id.split('(')[1].gsub(')','')
    end


    @current_city_user = CityUser.find_by_city_user_id(user_id)

    if @current_city_user.kind_of?(NilClass)
      #redirect_to root_url
      return
    end

    session[:city_user_id] = @current_city_user.city_user_id

    user = User.find_by_user_id(@current_city_user.city_user_id.to_s)
    if (user.nil?)
      user =User.create_with_city_user(@current_city_user)
    end

    if user.nil?
      render :text => "Unknown Error Occurred"
    end

    cookies[:user_id] = user.id
    session[:user_id] = user.id

    #Set Current Logon  User
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  def validate_event(event_id)
    event_id = Event.find(event_id) #Get Event id from params and verify it
                                    #Avoid SQL Injection
    Event.where("id= ? and start_date >= ? ",event_id.id,Time.now.strftime('%Y-%m-%d')).order("start_date desc").first
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:registration).permit(:event_id,:amount_total,:amount_payable,:max_price,
                                         :registration_addons_attributes => [:addon_id,:addon_value,:registration_choices_attributes =>[:choice_id,:choice_value,:choice_price]],
                                         :registration_guests_attributes => [:city_user_id,:first,:last,:email,:primary_phone,:address,:city,:state,:coming,:registration_addons_attributes => [:addon_id,:addon_value,:registration_choices_attributes =>[:choice_id,:choice_value,:choice_price]]])


  end

end

app/helpers/home_helper.rb
module HomeHelper

  def eventLink(event)
    status = event.status(current_user)
    if status == 'new'
      link_to event.title,event_registration_path(event.id) ,:class => 'clickEvent'
    elsif status  == 'registered'
      link_to event.title,'#'
    elsif status  == 'pending'
      link_to event.title,event_registration_summary_path(Registration.find_by_user_id_and_event_id(current_user.id,event.id)), :class => 'clickEvent'
    end

  end

  def eventStatus(status)
    if status == 'new'
      '<div class="tag blue">Register</div>'
    elsif status  == 'registered'
      '<div class="tag green">Registered</div>'
    elsif status  == 'pending'
      '<div class="tag yellow">Pending, pay now</div>'
    end
  end

  def current_route
    Rails.application.routes.router.recognize(request) do |route, _|
      return route.name.to_sym
    end
  end

  def current_tab_name
    route = request.env['PATH_INFO']
    if route =='/'
      '<span class="title">1. User Lookup</span>'
    elsif route.include? '/upcoming-events'
        ' <span class="title">2. Upcoming Events</span>'
    elsif route.include? '/event_registration'
      ' <span class="title">3. Registration</span>'
    elsif route.include? '/event_registration_summary'
      ' <span class="title">4. Summary</span>'
    else
        ' '
    end
  end

  def remaining(date)
    intervals = [["day", 1], ["hour", 24]]

    elapsed = DateTime.now - date

    tense = elapsed > 0 ? "since" : "until"

    interval = 1.0

    parts = intervals.collect do |name, new_interval|
                interval /= new_interval

                number, elapsed = elapsed.abs.divmod(interval)
                if number >0
                  "#{number.to_i} #{name}#{"s" unless number == 1}"
                end
            end
    parts = parts.reject{ |e| e.nil? }
   "#{parts.join(", ")}, Register thru "
  end

end

app/views/home/_footer.html.erb
<div class="grid_8 footer">
  <% if current_city_user.nil? %>
      <div class="row">
        <div class="small-12 medium-6 columns">
          Not a member? <a href="https://2rc.onthecity.org/kiosk/">Sign up here.</a>
        </div>
      </div>
  <% else %>
      <% if current_city_user.staff? %>
          <%= link_to 'Events Admin',admin_path,:class => 'btn .btn_go' %>
      <% end %>
  <% end %>
</div>

app/views/home/index.html.erb
<section id="user-lookup" class="row">
      <h1 class="small-12 columns">Hello, who are you?</h1>
      <%= simple_form_for @city_user, :url => upcoming_path, :method => :post do |f| %>
            <%= f.text_field :city_user_id, :placeholder => "John Smith...",:class => 'typeahead home-autocomplete medium-12 large-8 large-push-2 columns', 'data-autocomplete-url' => autocomplete_for_city_user_full_name_city_users_path %>
      <% end %>
      <p class="small-12 columns">Start typing your name then select your identity from the dropdown</p>
</section>

<div class="row">
  <div class="small-12 medium-6 columns">
    Not a member? <a href="https://2rc.onthecity.org/kiosk/">Sign up here.</a>
  </div>
</div>

app/views/home/registration.html.erb
<%= simple_form_for([@event, @registration],url: complete_registration_path ) do |f| %>
    <section id="event-registration" class="row">
      <!--Register for-->
      <h1><span class="icon"> </span> <%= @event.title %></h1>
      <!--BEGIN: ERROR BLOCK-->
      <div class="error prettyprint" style="display:none;">
        <img src="<%= request.protocol+request.host_with_port+image_path('warning.gif') %>" alt="Warning!" width="24" height="24" style="float:left; margin: -5px 10px 0px 0px; " />
        <span></span>.<br clear="all"/>
      </div>
      <% if @registration.errors.any? %>
          <div id="error_explanation" class="prettyprint">
            <h2><%= pluralize(@registration.errors.count, "error") %> prohibited this event from being saved:</h2>
            <ul>
              <% @registration.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <!--BEGIN: HIDDEN FIELD BLOCK-->
      <%= f.hidden_field :event_id %>
      <%= f.hidden_field :amount_total %>
      <%= f.hidden_field :amount_payable %>
      <%= f.hidden_field :max_price,:value => @event.max_price  %>

      <div class="left-sec small-12 medium-7 columns">

        <% if not @event.content.empty? %>
            <h2>Event Description</h2>
            <div>
                <%= @event.content.html_safe %>
            </div>
            <br /><br />
        <% end %>

        <h2>Who's Coming?</h2>
        <p>Click a person to register them and fill out their personal options.</p>
        <!--BEGIN Who is Coming Block-->
        <div class="added-users">
          <ul class="person-list">
            <%= render 'home/partials/person',:f => f,:registration => @registration,:person_id => current_user.user_id,:person_picture =>  person_image(current_user.gender) ,:person_name => current_user.user_name, :checked_state => false, :display_state => false %>
            <% @registration.family_members.each do |member| %>
                <%= render 'home/partials/person',:f => f,:registration => @registration,:person_id => member.city_user_id,:person_picture => person_image('female'),:person_name =>  member.name, :checked_state => false, :display_state => false %>
            <% end %>
          </ul>
        </div>
        <!--END Who is Coming Block-->
        <h3 style="margin-top: 1.5em;">Add More People</h3>
        <div class="search-users row">
          <%= f.text_field :city_users, :class => 'search autocomplete small-12 columns', 'data-autocomplete-url' => autocomplete_for_city_user_full_name_city_users_path,:placeHolder=>"Add registered City users to this event by searching here..." %>
          <%= link_to_add_person_specific_options f,@registration,"plus",'home/partials/person',1 %>
        </div>
        <div class="non-registered">
          <%= link_to_add_guest_specific_options 'Add a non-registered user',f,@registration,"addlink",'home/partials/guest' %> <span>(valid email required)</span>
          <span id="guests"> </span>
        </div>
        <div class="addons">
          <h3 style="margin-top: 1.5em;">Group Options</h3>

          <% @registration.registration_addons.each do |a| %>
              <%= f.simple_fields_for "registration_addons_attributes[#{a.addon.id}]", a do |addon_form| %>
                  <%= addon_form.hidden_field :addon_id %>
                  <%= render_addon_form_helper(a, addon_form,true) %>
              <% end %>
          <% end %>

        </div>
      </div>


      <div class="right-sec small-12 medium-5 columns">

        <h2>Summary</h2>
        <%= render 'home/partials/summary' %>

      </div>

      <div class="clr"></div>


    </section>
<% end %>
<script type="text/javascript">
    $(document).ready(function() {
        //Initailze Guest Count
        jQuery(document).data('tcEvents.guests', 0);

        jQuery("form").validate({
            invalidHandler: function(e, validator) {
                var errors = validator.numberOfInvalids();
                if (errors) {
                    var message = errors == 1
                            ? 'You missed 1 field. It has been highlighted below'
                            : 'You missed ' + errors + ' fields.  They have been highlighted below';
                    $("div.error span").html(message);
                    $("div.error").show();
                    setTimeout(function() {
                        $("div.error").hide('slow');
                    }, 2000);

                } else {
                    $("div.error").hide();
                }
            }
        });

        $( "#submit" ).click(function() {
            event.preventDefault();
            if ($("#who-view").find('li').length==0){
                $("div.error span").html("No person selected to register");
                $("div.error").show();
                setTimeout(function() {
                    $("div.error").hide('slow');
                }, 2000);
                return false;
            }

            $( "form" ).submit();
        });

        $(".non-registered .addlink").click(function(){
            $(".non-registered .form-nonregistered ").addClass('active');
        });

        $(".non-registered .form-nonregistered .removeuser").click(function(){
            $(".non-registered .form-nonregistered").removeClass('active');
        });


        $('.user .triggor').each(function() {
            var expander = $(this), trig = expander.prev('a.options'), collapser = expander.next('div.collapsable');
            trig.click(function() {
                collapser.toggle(500);
            });

        });


    });
</script>

app/views/home/summary.html.erb
<div class="row newSummary">
  <h1 class="small-12 columns text-center"><span class="icon"> </span> <%= @registration.event.title %> </h1>

  <h2 class="small-12 columns text-center">Registration Details</h2>
</div>

<section id="newSummary" class="row">
  <div class="small-12 medium-10 medium-push-1 columns">

    <div class="newCart">
      <% #Loop over guests  %>
      <% @registration.registration_guests.each do |member| %>
          <div class="row priceRow">
            <div class="newDes small-12 medium-8 medium-push-2 columns">
              <span class="name"><%= member.first+' '+ member.last %></span>
              <span class="newPrice"><%= "$%.2f" % @registration.event.base_price %></span>
            </div>
          </div>
      <% end %>

      <% #Loop over addons   %>
      <% @registration.summary.rows.each do |summary| %>
          <div class="row priceRow">
            <div class="newDes small-12 medium-8 medium-push-2 columns">
              <span class="addon"><%= summary[0] %></span>
              <span class="addonPrice"><%= "$%.2f" % summary[1] %></span>
            </div>
          </div>
      <% end %>

      <% #Coupons  %>
      <%= form_tag("/registrations/verify_coupon", method: "post", :remote => true) do %>
          <div class="couponRow">
            <div class="row">
              <div class="title small-8 medium-push-2 columns">
                Do you have a Coupon Code?
              </div>
            </div>


            <div class="row">
              <div class="small-12 medium-8 medium-push-2 columns">
                <%= text_field_tag(:coupon) %>
              </div>
            </div>

            <div class="row">
              <a id="applyCoupen" href="" class="link small-12 medium-8 medium-push-2 columns text-right">apply
                coupon</a>
            </div>

            <div class="row">
              <div id="verify_result" class="small-12 medium-8 medium-push-2 columns"></div>
            </div>

            <%= hidden_field_tag(:amount, @registration.amount_payable) %>
            <%= hidden_field_tag(:registration, @registration.id) %>

          </div>
      <% end %>

    </div>
  </div>

  <div class="small-12 medium-10 medium-push-1 columns">
    <div id="newTotal">
      Grand Total: <span id="grand_total"><%= "$%.2f" % @registration.amount_payable %></span>
    </div>
  </div>

  <div class="small-12 medium-10 medium-push-1 columns">
    <a id="checkout" href="#." class="green-btn">Complete CHECKOUT</a>
  </div>


  <form action="<%= TheCityEvents::FOXY_CART_URL %>" method="post" accept-charset="utf-8" id="foxycartform">

    <input type="hidden" id="name" name="<%= CartEncryption::cart_input_name('name', @registration.event.title, "#{@registration.id}_#{current_user.id}") %>" value="<%= @registration.event.title %>"/>
    <input type="hidden" id="price" name="<%= CartEncryption::cart_input_name('price', @registration.amount_payable, "#{@registration.id}_#{current_user.id}") %>" value="<%= @registration.amount_payable %>"/>
    <input type="hidden" id="code" name="<%= CartEncryption::cart_input_name('code', "#{@registration.id}_#{current_user.id}", "#{@registration.id}_#{current_user.id}") %>" value="<%= "#{@registration.id}_#{current_user.id}" %>"/>
    <input type="hidden" id="empty" name="empty" value="true" />
    <input type="hidden" id="cart" name="cart" value="checkout" />
    <input type="hidden" id="empty" name="empty" value="true"/>

  </form>

  <div class="note small-12 text-center columns">
       <%= link_to 'Made a mistake? Delete and restart.',registration_path(@registration,:redirect => upcoming_url),
                                data: { confirm: 'Are you sure?' },
                                :method => :delete,
                                :class => "red-btn" %>
    </div>

</section>

<script type="text/javascript">
    $('#checkout').click(
            function () {
                event.preventDefault();
                var grand_total = $('#grand_total').text();
                if (parseFloat(grand_total.toString().replace('$', '')) <= 0) {
                    alert('No Amount to Pay');
                    return false;
                }

                $('#foxycartform').trigger('submit');
            });

    $('#applyCoupen').click(
            function () {
                event.preventDefault();

                if ($("#coupon").val() == '') {
                    alert('Please enter coupon code to apply.');
                    return false;
                }

                $(this).closest('form').trigger('submit');
            });
</script>

app/views/home/upcoming.html.erb
<section id="upcoming-events">
  <div class="row">
      <h1 class="center"><span class="icon"> </span>Upcoming Events</h1>
      <%= simple_form_for upcoming_path,:method => 'get' do |f| %>
        <%= f.input :limit, :collection => [ ["Show 5 events",'5'] , [ "Show 10 events", '10'], [ "Show 15 events", '15']] ,selected: params[:limit] || '10'  , :label => false, :input_html => {:id => "limit",:name => "limit", :class => "small-12 medium-5 columns"} %>
        <%= f.input :title, :label => false, :input_html => {:id => "title",:name => "title", :value => params[:title], :placeholder => 'search events', :class => "small-12 medium-5 medium-push-2 columns"} %>
      <% end %>
  </div>


  <div class="clr"></div>
      <ul id="events">
        <%  @events.each do |event| %>
            <li style="cursor:pointer;" onclick="$(this).find('a').first()[0].click();" class="row" >
              <div class="small-9 medium-4 columns">
                <div class="date"><%= event.start_date.strftime("%d") %><span><%= Date::MONTHNAMES[event.start_date.month] %></span></div>
                <span class="title left"><%= eventLink(event) %></span>
              </div>

              <div class="small-6 medium-6 columns small-only-text-center">
                  Register thru
                  <%= Date::MONTHNAMES[event.start_date.month]+' '+ event.start_date.day.ordinalize %>
              </div>

                <div class='small-6 medium-2 columns'>
                  <%= eventStatus(event.status(current_user)).html_safe %>
                </div>

              <div class="clr"></div>
            </li>
        <% end %>
      </ul>

  <div class="navigation-links">
    <%= will_paginate @events, :page_links => false, :previous_label => '<',:next_label => '>' %>

  </div>

 <%= render "footer" %>

</section>

<script>
    $('#limit').change(
            function(){
                $(this).closest('form').trigger('submit');
            });

    $("#title").keypress(function(event) {
        if (event.which == 13) {
            event.preventDefault();
            $(this).closest('form').trigger('submit');
        }
    });


</script>