config/routes.rb
TheCityEvents::Application.routes.draw do

  get 'auth/failure'=> 'application#failure',:as => :failure

  post "webhooks/createCityUser"
  post "webhooks/createFamilyMember"

  resources :city_users do
    get :autocomplete_for_city_user_full_name, :on => :collection
  end

  resources :events do
    member do
      get 'register'
    end
  end

  resources :registrations do
    member do
      get 'summary'
    end
  end

  namespace :admin do
    resources :events
    resources :coupons
    get 'reports/summary/:id' => 'reports#summary',:as => :summary
    get 'reports/detail/:id' => 'reports#detail', :as => :detail

  end

  get  "/admin" => "admin/events#index"

  match "adminLogin" => "sessions#adminLogin",via: [:post]
  match "clientLogin" => "sessions#clientLogin",via: [:get,:post]

  match '/safari_cookie', to: 'sessions#safari_cookie' ,via: [:get,:post]

  match "/auth/:provider/callback" => "sessions#create",via: [:get]
  match "/signout" => "sessions#destroy", :as => :signo,via: [:get]

  match "registrations/verify_coupon" => "registrations#verify_coupon" ,via: [:post]

  match "registrations/redeem_coupon" => "registrations#redeem_coupon" ,via: [:post]

  match "/processfeed" => "datafeeds#parsefeed",via: [:post]

  match "upcoming-events" => "home#upcoming" , :as => "upcoming" ,via: [:get,:post]

  match "registration/:event_id" => "home#registration" , :as => "event_registration" ,via: [:get,:post]

  match "registration/:id/summary" => "home#summary" , :as => "event_registration_summary" ,via: [:get,:post]

  match "complete" => "home#create" , :as => "complete_registration" ,via: [:post]

  post "/" => "home#index"
  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :addons , :dependent => :destroy
  has_one :registration
  has_many :registrations

  accepts_nested_attributes_for :addons , :reject_if => lambda { |a| a[:title].blank? },:allow_destroy => true
  validates_presence_of :title, :start_date, :end_date, :start_time, :end_time, :base_price, :max_price, :seats

  validates_numericality_of :base_price,
                            :greater_than_or_equal_to =>0,
                            :message => "invalid base price"

  validates_numericality_of :max_price,
                            :greater_than_or_equal_to =>0,
                            :message => "invalid max price"

  validates_numericality_of :seats, :only_integer =>true,
                            :greater_than_or_equal_to =>0,
                            :message => "invalid seats"
  attr_accessor :status

  scope :all, where('archive = ?', :false)

  scope :archived, where('archive = ?', :true)


  def status(current_user)
   if(current_user.nil?)
     "new"
   else
     registration =Registration.find_by_user_id_and_event_id(current_user.id,self.id)
     if(registration)
       if registration.amount_paid >= registration.amount_payable
         "registered"
       elsif registration.amount_paid < registration.amount_payable
         "pending"
       end
     else
       "new"
     end
   end

  end

  #def exportCSV(options = {})
  #
  #  registrations =self.registrations.where("amount_paid=amount_payable")
  #
  #  CSV.generate(options) do |csv|
  #   # csv << ['date','registration','guests']
  #   registrations.each do |r|
  #     #registration
  #     row =[r.created_at.strftime("%m/%d/%Y"),r.user.user_name]
  #     #guests
  #     r.registration_guests.each do  |guest|
  #       row += [guest.first,guest.last,guest.address.blank? ? '-' : guest.address,guest.city.blank? ? '-' : guest.city,guest.state.blank? ? '-' : guest.state]
  #     end
  #     #addons
  #     r.registration_addons.each do |addon|
  #       row += [getTitle(addon, false)]
  #     end
  #
  #     csv << row
  #   end
  #
  #
  #
  #  end
  #
  #end

  def exportCSV(options = {})
    event = self
    registrations =event.registrations.where("amount_paid=amount_payable")

    CSV.generate(options) do |csv|
       #Header
       csv << ['Date','Registration','Coupon','Total']+addons_headings(event, true)+['Guests']+addons_headings(event, false) #+['Guest Total']
       registrations.each do |r|
         #Date and registration Field
         row =[r.created_at.strftime("%m/%d/%Y"),r.user.user_name,r.coupon==''? ' ' : r.coupon+'('+"$%.2f" % r.coupon_amount+')',"$%.2f" % r.amount_payable]
         #addon values for registration specific Fields
         row += registration_specific_choices(event, r)


         #add guests
         price =0.00
         r.registration_guests.each.with_index do |guest,index|
           #addons place holders for registrant specific Fields
           row2 =[]
           if(index>0)
             row2 +=[' ',' ',' ',' ']
             row2 += addons_headings_placeholder(event, true)
           end
           row2  +=[guest.first+' '+guest.last]
           event.addons.where(:registration_type => false).each do |a|
               addon =guest.registration_addons.where(:addon_id => a.id).first
               if addon
                 row2.push(getTitle(addon, false))
               else
                 row2.push(' ')
               end
           end

           #Guest Total
           #a = RegistrationAddon.where(:registration_guest_id => guest.id).joins(:registration_choices).sum("choice_value*choice_price")
           #row2.push( a>0 ? "$ %.2f" % a : ' ')

           if(index==0)
             #First Row
             csv << row+row2
           else
             csv << row2
           end

         end


       end


    end

  end

  def addons_headings(event, state)
    result =[]
    event.addons.where(:registration_type => state).each do |a|
      result.push(a.title)
    end
    result
  end

  def addons_headings_placeholder(event, state)
    result =[]
    event.addons.where(:registration_type => state).each do |a|
      result.push('')
    end
    result
  end

  def registration_specific_choices(event, r)
    choices=[]
    event.addons.where(:registration_type => true).each do |a|
      addon =r.registration_addons.where(:addon_id => a.id).first
      choices.push(getTitle(addon, false))
    end
    choices
  end





  def getTitle(a, empty)

    case a.addon.addon_type
      when "Addons::Text"
        a.addon_value=='' ? ' ' : a.addon_value
      when "Addons::Dropdown"
        a.addon_value=='' ? ' ' : Choice.find_by_id(a.addon_value) ? Choice.find_by_id(a.addon_value).title : ' '
      when "Addons::Checkbox"
        choices = a.registration_choices.where(:choice_value => 1)
        if choices.count>0
          choices.map { |c| c.choice.title }.join ','
        else
          "-"
        end
      when "Addons::Scale"
        choices = a.registration_choices
        if choices.count>0
          choices.map { |c| "#{c.choice.title}-#{c.choice_value.nil? ? 0 : c.choice_value }" }.join ' | '
        else
          empty ? "" : " "
        end
      else
        a.addon.addon_type
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

require 'addon_form'
  def index
    @events = Event.all.order(start_date: :desc)
  end
  def show
    @event = Event.find(params[:id])
  end
  def new
    @admin_event = Event.new
    1.times do
      addon = @admin_event.addons.build
      1.times { addon.choices.build }
    end
  end

  # POST /events
  # POST /events.json
  def create

    @admin_event = Event.new(event_params)

    respond_to do |format|
      if @admin_event.save
        format.html { redirect_to admin_events_url, notice: 'Event was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy

    Event.find(params[:id]).update :archive => true

    return redirect_to admin_events_url, notice: 'Event was successfully deleted.'

  end
  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :start_date, :end_date, :start_time, :end_time, :base_price, :max_price, :seats,:content,addons_attributes: [:addon_type,:registration_type,:title,:_destroy,choices_attributes:[:title,:price,:range_from,:range_to,:_destroy]])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def index

    @registered_events = current_user.events.where("amount_paid=amount_payable")
    @pending_registrations = current_user.events.where("amount_paid<>amount_payable")

    @up_coming_events= Event.where("start_date > ? and id NOT IN (?)",Time.now.strftime('%Y-%m-%d'),current_user.events.select("events.id").load).order("start_date desc").load

  end

  def show
    begin
      @event =current_user.events.find(params[:id])
    rescue
      redirect_to events_path, :notice => "Well, that wasn't supposed to happen."
    end

  end

  def register

    @event = validate_event(params[:id])

    if @event.nil?
      redirect_to events_path, :notice => "Sorry, event has been passed."
      return
    end

    @registration = Registration.new(:event => @event)

    @registration.family_members = current_user.family_members.where('city_user_id != ?', current_user.user_id).all(:order => :city_user_id)

    @event.addons.order('id').collect do |addon|
      a= @registration.registration_addons.build(addon_id: addon.id)
      addon.choices.order('id').collect do |choice|
        a.registration_choices.build(choice_id: choice.id,choice_price: choice.price)
      end
    end


  end

  #Creates a new event
  def create

    @registration = current_user.registrations.new(event_params)

    respond_to do |format|
      if @registration.save
        if @registration.amount_payable == 0.0
          format.html { redirect_to :controller => 'events', notice: 'Event was successfully registered.'  }
        else
          format.html { redirect_to :controller => 'registrations', :action => 'summary', :id => @registration.id,notice: 'Event was successfully registered.' }
        end

      else
        @event =validate_event(event_params[:event_id])
        @registration.family_members = current_user.family_members.where('city_user_id != ?', current_user.user_id).all(:order => :city_user_id)
        format.html { render action: 'register' }
      end
    end

  end


  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:registration).permit(:event_id,:amount_total,:amount_payable,:max_price,
                                         :registration_addons_attributes => [:addon_id,:addon_value,:registration_choices_attributes =>[:choice_id,:choice_value,:choice_price]],
                                         :registration_guests_attributes => [:city_user_id,:first,:last,:email,:primary_phone,:address,:city,:state,:coming,:registration_addons_attributes => [:addon_id,:addon_value,:registration_choices_attributes =>[:choice_id,:choice_value,:choice_price]]])


  end

  def validate_event(event_id)
    event_id = Event.find(event_id) #Get Event id from params and verify it
    #Avoid SQL Injection
    Event.where("id= ? and start_date >= ? ",event_id.id,Time.now.strftime('%Y-%m-%d')).order("start_date desc").first
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def person_image(gender,imgDefault="no_image_male.jpg")
    image =imgDefault

    if gender == 'Male'
      image =imgDefault
    end

    if gender == 'Female'
        image =imgDefault
    end


    request.protocol+request.host_with_port+image_path(image)
  end

  #Function to choose which partial to render based on controller for Event Registration views
  def render_addon_form_helper(a, addon_form,type)
    if a.addon.registration_type==type
      partial = a.addon.addon_type.to_s.split("::").last.downcase
      #If using the outside-City controller ("Home") render one partial, otherwise use in-City partial
      if params[:controller]=='home'
        render partial: "home/addons/#{partial}", locals: { addon_form: addon_form, a: a }
      else
        render partial: "events/addons/#{partial}", locals: { addon_form: addon_form, a: a }
      end
    end
  end

  def fields_person_specific_options(f,registration)
     render(partial: "events/person_options", locals: { :f => f,:registration => registration,:person_id => "",:person_id_name=>"",:display_state => true })
  end

  def link_to_add_person_specific_options(f,registration,cssClass="left btn btn_mini",personTemplate='events/person',defaultAction=0)

    person =render(partial: personTemplate,locals: {:f => f,:registration => registration, :person_id => "{demo_id}",
                                                    :person_picture => person_image('no_image_male.jpg'),
                                                    :person_name =>  "{demo_name}",
                                                    :checked_state => true,
                                                    :display_state => true})

    fields =fields_person_specific_options(f,registration)

    if(cssClass=='plus')
      link_to  '', 'javascript:void(0);',
               :onclick => h("add_person_fields(this, \"#{registration}\", \"#{escape_javascript(fields)}\",\"#{escape_javascript(person)}\",#{defaultAction});"),
               :class => cssClass
    else
      link_to image_tag('add_icon.png', :border=>0,:alt=>'Add_icon', :style => 'margin-right: 3px; float: left;'), 'javascript:void(0);',
              :onclick => h("add_person_fields(this, \"#{registration}\", \"#{escape_javascript(fields)}\",\"#{escape_javascript(person)}\",#{defaultAction});"),
              :class => cssClass
    end




  end
  def link_to_toggle_person(f,registration,person_id,person_name)
    h("personCartToggle(this,\"#{person_id}\",\"#{person_name}\",\"#{registration}\",\"#{escape_javascript(fields_person_specific_options(f,registration))}\");")
  end

  def link_to_add_guest_specific_options(name,f,registration,cssClass="",guestPartial='events/guest')

    guest =render(partial: guestPartial,locals: { :f => f,:registration => registration})

    fields= render(partial: "events/person_options", locals: { :f => f,:registration => registration,:person_id => "{guest_id}",:person_id_name=>"{guest_name}",:display_state => true })


    link_to name, 'javascript:void(0);',
            :class => cssClass,
            :onclick => h("addGuest(\"#{registration}\", \"#{escape_javascript(fields)}\",\"#{escape_javascript(guest)}\");")

  end

  def add_choice_data_attributes(c)
    " data-title = #{c.choice.title}\ data-price = #{c.choice_price} "
  end
end

app/views/events/_event_header.erb
<ul style="display: none">
  <li class="grid-6-12"><strong>Start Date:</strong> <%= @event.start_date.strftime("%m/%d/%Y") %></li>
  <li class="grid-6-12"><strong>End Date:</strong> <%= @event.end_date.strftime("%m/%d/%Y") %></li>
  <li class="grid-6-12"><strong>Start Time:</strong> <%= @event.start_time.strftime("%I:%M%p") %></li>
  <li class="grid-6-12"><strong>End Time:</strong> <%= @event.end_time.strftime("%I:%M%p") %></li>
  <li class="grid-2-12"><strong>Base Price:</strong> <%= @event.base_price %></li>
  <li class="grid-2-12"><strong>Max Price:</strong> <%= @event.max_price %></li>
  <li class="grid-8-12"><strong>Seats:</strong> <%= @event.seats %></li>
</ul>

app/views/events/_footer.html.erb
<div class="grid_8 footer">
    <% if current_user.nil? %>
        Sign in
    <% else %>
      <% if !current_city_user.nil? %>
        <% if current_city_user.staff == true %>
            <%= link_to 'Admin',admin_events_path,:class => 'btn .btn_go' %>
        <% end %>
      <% end %>
    <% end %>
</div>

app/views/events/_guest.erb
<%= stylesheet_link_tag "events_guest", :media => "all" %>

<%= f.simple_fields_for "registration_guests_attributes[{guest_id}]", RegistrationGuest.new do |guest_form| %>
  <% parent_name = guest_form.object_name %>

  <fieldset id="guestTemplate">
    <ul >
      <h4 class='nolead'>{guest_name}</h4>
      <li class="grid-12-12">
        <%= guest_form.input :first, required: true %>
      </li>
      <li class="grid-12-12">
        <%= guest_form.input :last, required: true %>
      </li>
      <li class="grid-12-12">
        <%= guest_form.input :email %>
      </li>
      <li class="grid-12-12">
        <%= guest_form.input :primary_phone, required: true  %>
      </li>
      <li class="grid-12-12">
        <%= guest_form.input :address %>
      </li>
      <li class="grid-12-12">
         <%= guest_form.input :city %>
      </li>
      <li class="grid-12-12">
          <%= guest_form.input :state %>
      </li>
      <li class="grid-12-12">
        <input type="checkbox" name="<%= parent_name %>[coming]"
               id="<%= parent_name %>[coming]"
               checked
               class="person"
               data-item-amount='<%= @event.base_price > 0 ? '%.2f' % @event.base_price : '0.00' %>'
               onchange="removeGuest(this,'{guest_id}');"
               />
        <span class="overlay"></span>
        <a id='remove_guest_' href="javascript:void(0);"><label for='<%= parent_name %>[coming]' class='right'>-Remove Guest</label></a>
      </li>
    </ul>
  </fieldset>

<% end %>

app/views/events/_header.erb
<header class="center_stage">
  <h1>Event Registration</h1>

  <p>
    <% if current_user.nil? %>
        Sign in
    <% else %>
        Welcome,<%= "#{current_user.first} #{current_user.last}" %>
    <% end %>
  </p>

  <div class="context_bar"></div>
</header>
<% if !params[:notice].blank? %>
    <div class="prettyprint">
      <%= params[:notice] %>
    </div>
<% end %>

app/views/events/_pending_registrations.erb
<br/><br/><br/>
<% if @pending_registrations.count >0  %>
    <h3 class="rule">Pending Registrations</h3>
    <table id="registered_events"  class='datatable with_stripes"'>
      <thead>
      <tr>
        <th colspan="2">Title</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Start Time</th>
        <th>End Time</th>
      </tr>
      </thead>
      <tbody>
      <% @pending_registrations.each do |event| %>
          <tr id="<%= dom_id(event) %>">
            <% reg =Registration.find_by_user_id_and_event_id(current_user.id,event.id) %>
            <td><%= event.title %></td>
            <td><%= link_to 'Pay Now',"registrations/#{reg.id}/summary",:class => "btn  btn_mini" %></td>
            <td><%= event.start_date.strftime("%m/%d/%Y") %></td>
            <td><%= event.end_date.strftime("%m/%d/%Y") %></td>
            <td><%= event.start_time.strftime("%I:%M%p") %></td>
            <td><%= event.end_time.strftime("%I:%M%p") %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <span></span>
<% end %>

app/views/events/_person.erb
<li class="grid-12-12 checkbox-person" data-person="<%= person_name %>">
  <%= f.simple_fields_for "registration_guests_attributes[#{person_id}]", RegistrationGuest.new do |person_form| %>
      <%= person_form.input :city_user_id, :input_html => {:value => person_id}, :as => :hidden %>
      <%= person_form.input :first, :input_html => {:value => person_name.split[0]}, :as => :hidden %>
      <%= person_form.input :last, :input_html => {:value => person_name.split[1]}, :as => :hidden %>

      <label for="<%= person_form.object_name %>[coming]">
                  <span class="checkbox" style="background-image: url(<%= person_picture %>)">
                    <input type="checkbox" name="<%= person_form.object_name %>[coming]" id="<%= person_form.object_name %>[coming]" <%= checked_state ? "checked" : "" %> class="person"
                           data-person-name='<%= person_name %>'
                           data-item-amount='<%= @event.base_price > 0 ? '%.2f' % @event.base_price : '0.00' %>'
                           onchange="<%= link_to_toggle_person(f,registration,person_id,person_name)  %>"/>
                    <span class="overlay"></span>
                </span>
        <h4><%= person_name %> (<%= person_id==current_user.user_id ? "You" : "" %> <%= @event.base_price > 0 ? '$%.2f' % @event.base_price : '$0.00' %>)</h4>
      </label>

  <% end %>

</li>

app/views/events/_person_options.erb
<% if @event.addons.where(:registration_type => :false).count>0 %>

<fieldset class="options-person" data-for-person-id="<%= person_id %>" data-for-person-name="<%= person_id_name %>" style="<%= display_state ? "display:block;" : "display:none;" %> " >
  <h2 class="rule">Options for <span class="person-name"><%= person_id_name %></span></h2>

  <% registration.registration_addons.each do |a| %>

      <%= f.simple_fields_for "registration_guests_attributes[#{ person_id}][registration_addons_attributes[#{a.addon.id}]]", a do |addon_form| %>
          <%= render_addon_form_helper(a, addon_form,false) %>
          <%= addon_form.hidden_field :addon_id %>
      <% end %>
  <% end %>
</fieldset>
<% end %>

app/views/events/_registered_events.erb
<br/><br/><br/>
<% if @registered_events.count >0  %>
    <h3 class="rule">Events You've Registered For</h3>
    <table id="registered_events"  class='datatable with_stripes autosort'>
      <thead>
      <tr>
        <th>Title</th>
        <th data-autosort="true" data-sortdir="asc">Start Date</th>
        <th>End Date</th>
        <th>Start Time</th>
        <th>End Time</th>
      </tr>
      </thead>
      <tbody>
      <% @registered_events.each do |event| %>
          <tr id="<%= dom_id(event) %>">
            <% reg =Registration.find_by_user_id_and_event_id(current_user.id,event.id) %>
            <td><%= link_to event.title,registration_path(reg.id) %></td>
            <td><%= event.start_date.strftime("%m/%d/%Y") %></td>
            <td><%= event.end_date.strftime("%m/%d/%Y") %></td>
            <td><%= event.start_time.strftime("%I:%M%p") %></td>
            <td><%= event.end_time.strftime("%I:%M%p") %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <h3 class="rule">You have not registered any events yet!</h3>
<% end %>

app/views/events/_summary.erb
<div id="summary-main" class="grid_3 omega">
  <div id="summary-view" class="wrapper">
    <h2 class="rule">Registration</h2>

    <div id="who-view" class="wrapper">
      <h4>Who you have selected:</h4>
      <!--<li id="<%#= current_user.user_id %>_person"><%#= current_user.user_name %>&nbsp;&nbsp;&nbsp;<span id="5.0" class="item-price-summary"><%#= @event.base_price > 0 ? '$%.2f' % @event.base_price : '' %></span></li>-->
    </div>
    <br/>
    <div id="what-view" class="wrapper">
      <h4>What you have selected:</h4>
    </div>
  </div>
  <div class="rule guttertop"></div>

  <h4 id="totalCartAmountHolder">
    <span id="total_summary"></span>
  </h4>
  <!--<h4>Max Limit: <%#= "$%.2f" % @event.max_price %> </h4>-->
</div>

app/views/events/_upcoming_events.erb
<% if @up_coming_events.count >0  %>
    <h3 class="rule">Upcoming Events</h3>
    <table id="upcoming_events" class='datatable with_stripes autosort'>
      <thead>
      <tr>
        <th>Title</th>
        <th data-autosort="true" data-sortdir="desc">Start Date</th>
        <th>End Date</th>
        <th>Start Time</th>
        <th>End Time</th>
      </tr>
      </thead>
      <tbody>
      <%  @up_coming_events.each do |event| %>
          <tr id="<%= dom_id(event) %>">
            <td><%= link_to event.title,register_event_path(event.id) %></td>
            <td><%= event.start_date.strftime("%m/%d/%Y") %></td>
            <td><%= event.end_date.strftime("%m/%d/%Y") %></td>
            <td><%= event.start_time.strftime("%I:%M%p") %></td>
            <td><%= event.end_time.strftime("%I:%M%p") %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <h3 class="rule">There are no more upcoming events</h3>
<% end %>

app/views/events/index.html.erb
<%= render 'header' %>


<%= render 'upcoming_events' %>
<%= render 'pending_registrations' %>
<%= render 'registered_events' %>

<%= render 'footer' %>

app/views/events/register.erb
<header class="center_stage">
  <h1> Register for <%= @event.title %></h1>
  <div class="context_bar"></div>
</header>
<div class="grid_5">

  <%= simple_form_for([@event, @registration],url: events_path ) do |f| %>
      <div class="error prettyprint" style="display:none;">
        <img src="<%= request.protocol+request.host_with_port+image_path('warning.gif') %>" alt="Warning!" width="24" height="24" style="float:left; margin: -5px 10px 0px 0px; " />
        <span></span>.<br clear="all"/>
      </div>
      <% if @registration.errors.any? %>
          <div id="error_explanation" class="prettyprint">
            <h2><%= pluralize(@registration.errors.count, "error") %> prohibited this event from being saved:</h2>
            <ul>
              <% @registration.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <fieldset style="background-image:none;">

        <%= f.hidden_field :event_id %>
        <%= f.hidden_field :amount_total %>
        <%= f.hidden_field :amount_payable %>
        <%= f.hidden_field :max_price,:value => @event.max_price  %>

        <% if not @event.content.nil? %>
            <ul class="formee-list">
                <li class="grid-12-12"><h3 class="rule">About</h3></li>
                <li class="grid-12-12"><%= @event.content.html_safe %></li>
            </ul>
        <% end %>

        <ul class="formee-list">
          <%= render 'event_header' %>

          <h3 class="rule">Who is coming?</h3>

          <ul class="person-list">
            <%= render 'events/person',:f => f,:registration => @registration,:person_id => current_user.user_id,:person_picture =>  person_image(current_user.gender) ,:person_name => current_user.user_name,:checked_state => false %>
            <% @registration.family_members.each do |member| %>
                <%= render 'events/person',:f => f,:registration => @registration,:person_id => member.city_user_id,:person_picture => person_image('female'),:person_name =>  member.name,:checked_state => false %>
            <% end %>
          </ul>


          <h5 class="rule">Add a Guest Already in The City</h5>
          <label class="block">Search for a user</label>
          <ul>
            <li class="grid-10-12">
              <%= f.text_field :city_users, :class => 'autocomplete', 'data-autocomplete-url' => autocomplete_for_city_user_full_name_city_users_path %>
            </li>
            <li class="grid-2-12">
                <%= link_to_add_person_specific_options f,@registration %>
            </li>
            <li class="grid-12-12">
              <h3 class="guttertop">
                <%= link_to_add_guest_specific_options '+Add a Guest Not on The City',f,@registration %>
              </h3>
            </li>
          </ul>

          <span id="guests"> </span>

          <div class="addons">

            <% @registration.registration_addons.each do |a| %>
                <%= f.simple_fields_for "registration_addons_attributes[#{a.addon.id}]", a do |addon_form| %>
                    <%= addon_form.hidden_field :addon_id %>
                    <%= render_addon_form_helper(a, addon_form,true) %>
                <% end %>
            <% end %>

          </div>
          <li class="form_footer">
            <%= f.submit :class => 'left btn btn_go' %>
            <%= link_to "Cancel",root_path,:class => "btn btn_cancel left" %>
          </li>

        </ul>
      </fieldset>
  <% end %>

</div>

<%= render 'summary' %>


<script>
    jQuery(document).ready(function(){
        jQuery(document).data('tcEvents.guests', 0);
        jQuery("form").validate({
            invalidHandler: function(e, validator) {
                var errors = validator.numberOfInvalids();
                if (errors) {
                    var message = errors == 1
                            ? 'You missed 1 field. It has been highlighted below'
                            : 'You missed ' + errors + ' fields.  They have been highlighted below';
                    $("div.error span").html(message);
                    $("div.error").show();
                } else {
                    $("div.error").hide();
                }
            }
        });

    })

</script>

app/views/events/show.erb
<header class="center_stage">
  <h1><%= @event.title %> Summary</h1>
  <div class="context_bar"></div>
</header>